import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from 'next/link';
import NavBar from "@/components/NavBar";

import '@farcaster/auth-kit/styles.css';
import { SignInButton, AuthKitProvider } from '@farcaster/auth-kit';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const config = {
  rpcUrl: 'https://mainnet.optimism.io',
  domain: 'localhost:3000',
  siweUri: 'https://example.com/login',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthKitProvider config={config}>
        <body className={`${inter.className} box-border h-screen min-h-screen`}>
          <div className="flex justify-center items-start">
            
            {/* Side Bar */}
            <nav className="p-6 pt-16 w-52 h-screen">
              <NavBar />
            </nav>

            {/* Main Page */}
            <div className="p-6 pt-16 w-5/12 h-screen border-x-2 border-black">
              {children}
            </div>

            {/* Right Side Bar */}
            <div>
              <SignInButton />
            </div>
            
          </div>
        </body>
      </AuthKitProvider>
    </html>
  );
}
