import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavMenu from "@/components/NavMenu";
import LoginButton from "@/components/LoginButton";
import AuthKitProvider from '@/components/AuthKitProvider';
import { getServerSession } from "next-auth";
import SessionProvider from '@/components/SessionProvider';

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const config = {
  rpcUrl: 'https://mainnet.optimism.io',
  domain: 'localhost:3000',
  siweUri: 'localhost:3000',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await getServerSession();

  return (
    <html lang="en">
      <body className={`${inter.className} box-border h-screen min-h-screen`}>
        <SessionProvider session={session}><AuthKitProvider config={config}>
          <div className="flex justify-center items-start">
            
            {/* Side Bar */}
            <nav className="p-2 px-4 w-52 h-screen">
              <NavMenu />
            </nav>

            {/* Main Page */}
            <div className="p-2 w-5/12 h-screen border-x-2 border-black">
              {children}
            </div>

            {/* Right Side Bar */}
            <div className="p-2">
              
            </div>

          </div>
        </AuthKitProvider></SessionProvider>
      </body>
    </html>
  );
}
